# Generated by Django 3.2.4 on 2021-06-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalFileContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legal_file_contact', to='contacts.contact')),
                ('subtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legal_file_contact_role', to='contacts.contactsubtype')),
            ],
        ),
        migrations.CreateModel(
            name='LegalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('contactrole', models.ManyToManyField(blank=True, related_name='contactroles', to='legalfiles.LegalFileContactRole')),
            ],
        ),
    ]
